# Generated by Django 6.0 on 2026-04-27 20:10

import apps.beneficiarios.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Cédula (V)'), ('J', 'Jurídico (J)'), ('E', 'Extranjero (E)'), ('G', 'Gubernamental (G)')], default='V', max_length=1)),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='Cédula o RIF')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, verbose_name='Género')),
                ('discapacidad', models.BooleanField(default=False, verbose_name='¿Posee alguna discapacidad?')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('direccion_especifica', models.TextField(verbose_name='Dirección Específica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.ciudad')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.comuna')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.municipio')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.beneficiarios.models.ruta_expediente_universal)),
                ('categoria', models.CharField(choices=[('ID', 'Documento de Identidad'), ('CV', 'Síntesis Curricular (Personal)'), ('TIT', 'Títulos y Certificaciones'), ('CON', 'Contrato / Nombramiento'), ('RIF', 'RIF Vigente'), ('OTRO', 'Otros Documentos')], default='ID', max_length=4)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='beneficiarios.beneficiario')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_institucionales', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Documento Digital',
                'verbose_name_plural': 'Expedientes Digitales',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(choices=[('ASESORIA', 'Asesoría'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiros de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('REG_COMERCIAL', 'Regularización Comercial'), ('CTU', 'Registro O Actualización de CTU'), ('REG_TIERRAS', 'Regularización de Tierras o Vivienda'), ('TECNICO', 'Servicios Técnicos'), ('OTRO', 'Otros')], max_length=20)),
                ('funcionario_atiende', models.CharField(blank=True, max_length=255, null=True, verbose_name='Funcionario que lo atiende')),
                ('descripcion', models.TextField(verbose_name='Observaciones de la visita')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='beneficiarios.beneficiario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
