# Generated by Django 6.0 on 2026-01-20 14:17

import apps.beneficiarios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Cédula (V)'), ('J', 'Jurídico (J)'), ('E', 'Extranjero (E)'), ('G', 'Gubernamental (G)')], default='V', max_length=1)),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='Cédula o RIF')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.beneficiarios.models.ruta_expediente_digital)),
                ('nombre_documento', models.CharField(help_text='Ej: Copia de CI, RIF Vigente, etc.', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='beneficiarios.beneficiario')),
            ],
        ),
    ]
