# Generated by Django 6.0 on 2026-02-03 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(choices=[('ASESORIA', 'Asesoría Jurídica'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiro de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('OTRO', 'Otro / Información General')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Observaciones de la visita')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='beneficiarios.beneficiario')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
