# Generated by Django 6.0 on 2026-03-15 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_visita'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ciudad',
            field=models.CharField(default=1, max_length=100, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='comuna',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='direccion_especifica',
            field=models.TextField(default=1, verbose_name='Dirección Específica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='¿Posee alguna discapacidad?'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], default=1, max_length=1, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='parroquia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.parroquia'),
            preserve_default=False,
        ),
    ]
