# Generated by Django 6.0 on 2026-03-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_beneficiario_ciudad_beneficiario_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, verbose_name='Género'),
        ),
    ]
