# Generated by Django 6.0 on 2026-09-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_remove_otro_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('ASESORIA_AVV', 'Asesoría AVV'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiros de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('SOL_INAVI', 'Solicitud Regularización INAVI'), ('SOL_LINDEROS', 'Solicitud de Linderos'), ('ACL_LINDEROS', 'Aclaratorias de Linderos INAVI'), ('RESP_TRIB_SUP', 'Respuesta a Tribunales - Títulos Supletorios'), ('LIB_TERR', 'Liberaciones de Terrenos'), ('TRF_TERR', 'Transferencia de Terrenos'), ('SOL_INSPECCION', 'Solicitud de Inspección'), ('REG_COMERCIAL', 'Regularización Comercial'), ('CTU', 'Registro O Actualización de CTU'), ('REG_TIERRAS', 'Regularización de Tierras o Vivienda'), ('TECNICO', 'Servicios Técnicos')], max_length=20),
        ),
    ]
