# Generated by Django 6.0 on 2026-03-16 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_alter_beneficiario_genero'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.ciudad'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='territorio.comuna'),
        ),
    ]
