# Generated by Django 6.0 on 2026-03-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0005_alter_beneficiario_ciudad_alter_beneficiario_comuna'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoexpediente',
            options={'verbose_name': 'Documento Digital', 'verbose_name_plural': 'Expedientes Digitales'},
        ),
        migrations.AddField(
            model_name='documentoexpediente',
            name='categoria',
            field=models.CharField(choices=[('ID', 'Documento de Identidad'), ('CV', 'Síntesis Curricular (Personal)'), ('TIT', 'Títulos y Certificaciones'), ('CON', 'Contrato / Nombramiento'), ('RIF', 'RIF Vigente'), ('OTRO', 'Otros Documentos')], default='ID', max_length=4),
        ),
        migrations.AddField(
            model_name='documentoexpediente',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_institucionales', to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='beneficiarios.beneficiario'),
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='nombre_documento',
            field=models.CharField(help_text='Ej: Copia de CI, Título de Abogado, etc.', max_length=100),
        ),
    ]
