# Generated by Django 6.0 on 2026-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0005_alter_visita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('ASESORIA_AVV', 'Asesoría AVV'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiros de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('SOL_INAVI', 'Solicitud Regularización INAVI'), ('SOL_LINDEROS', 'Solicitud de Linderos'), ('ACL_LINDEROS', 'Aclaratorias de Linderos INAVI'), ('RESP_TRIB_SUP', 'Respuesta a Tribunales - Títulos Supletorios'), ('LIB_TERR', 'Liberaciones de Terrenos'), ('TRF_TERR', 'Transferencia de Terrenos'), ('SOL_INSPECCION', 'Solicitud de Inspección'), ('REG_COMERCIAL', 'Regularización Comercial: Consignación de recaudos, Inspección del local comercial, Regularización comercial'), ('CTU', 'CTU: Registro de CTU, Actualización de CTU, Corrección y asistencia jurídica al CTU'), ('REG_TIERRAS', 'Regularización de Tierras o Vivienda'), ('TECNICO', 'Servicios Técnicos'), ('ATENCIONES_AVV', 'Atenciones AVV Técnicas y Jurídicas'), ('INF_PREF', 'Informes de Prefactibilidad'), ('INSP_TERRENO', 'Inspección del Terreno'), ('TOPOGRAFIA', 'Topografía'), ('EST_SUELO', 'Estudios de Suelo'), ('REG_EXT_INAVI', 'Regularización Extinto INAVI'), ('EXPEDIENTE', 'Expediente (Consignación)'), ('INSP_LINDEROS', 'Inspección para Linderos'), ('AUT_PAGO', 'Autorización de Pago'), ('LIB_TIT_SUP', 'Liberaciones de Título Supletorio'), ('ACLARATORIA', 'Aclaratoria'), ('AUT_TIT_SUP', 'Autorización para Título Supletorio')], max_length=20),
        ),
    ]
