# Generated by Django 6.0 on 2026-03-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0006_alter_documentoexpediente_options_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='funcionario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_realizadas', to='personal.personal', verbose_name='Funcionario que atiende'),
        ),
    ]
