# Generated by Django 6.0 on 2026-03-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0007_visita_funcionario_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='funcionario_asignado',
        ),
    ]
