# Generated by Django 6.0 on 2026-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0007_alter_visita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('ATENCIONES_AVV', 'Atenciones AVV Técnicas y Jurídicas'), ('INFORMES_PREF', 'Informes de Prefactibilidad'), ('INSPECCION_TERRENO', 'Inspección del Terreno'), ('TOPOGRAFIA', 'Topografía'), ('ESTUDIOS_SUELO', 'Estudios de Suelo'), ('CTU_REGISTRO', 'CTU: Registro de CTU'), ('CTU_ACTUALIZACION', 'CTU: Actualización de CTU'), ('CTU_CORRECCION', 'CTU: Corrección y asistencia jurídica al CTU'), ('REG_COMERCIAL_CONSIGNACION', 'Regularización Comercial: Consignación de recaudos'), ('REG_COMERCIAL_INSPECCION', 'Regularización Comercial: Inspección del local comercial'), ('REG_COMERCIAL_REGULARIZACION', 'Regularización Comercial: Regularización comercial'), ('REG_EXT_INAVI', 'Regularización Extinto INAVI'), ('SOLICITUD', 'Solicitud'), ('STATUS_SOLICITUDES', 'Status de solicitudes'), ('REUNION', 'Reunión'), ('ASESORIAS', 'Asesorías'), ('OTROS', 'Otros'), ('EXPEDIENTE_CONSIGNACION', 'Expediente (Consignación)'), ('INSP_LINDEROS', 'Inspección para Linderos'), ('AUT_PAGO', 'Autorización de Pago'), ('LIB_TIT_SUP', 'Liberaciones de Título Supletorio'), ('ACLARATORIA', 'Aclaratoria'), ('AUT_TIT_SUP', 'Autorización para Título Supletorio'), ('TRF_TERR', 'Transferencia de Terrenos'), ('SOL_LINDEROS', 'Solicitud de Linderos')], max_length=80),
        ),
    ]
