# Generated by Django 6.0 on 2026-10-06 14:31

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


CATEGORIAS_ACTUALES = [
    ('ATENCIONES_AVV', 'Atenciones AVV Técnicas y Jurídicas'),
    ('INFORMES_PREF', 'Informes de Prefactibilidad'),
    ('INSPECCION_TERRENO', 'Inspección del Terreno'),
    ('TOPOGRAFIA', 'Topografía'),
    ('ESTUDIOS_SUELO', 'Estudios de Suelo'),
    ('CTU_REGISTRO', 'CTU: Registro de CTU'),
    ('CTU_ACTUALIZACION', 'CTU: Actualización de CTU'),
    ('CTU_CORRECCION', 'CTU: Corrección y asistencia jurídica al CTU'),
    ('REG_COMERCIAL_CONSIGNACION', 'Regularización Comercial: Consignación de recaudos'),
    ('REG_COMERCIAL_INSPECCION', 'Regularización Comercial: Inspección del local comercial'),
    ('REG_COMERCIAL_REGULARIZACION', 'Regularización Comercial: Regularización comercial'),
    ('REG_EXT_INAVI', 'Regularización Extinto INAVI'),
    ('SOLICITUD', 'Solicitud'),
    ('STATUS_SOLICITUDES', 'Status de solicitudes'),
    ('REUNION', 'Reunión'),
    ('ASESORIAS', 'Asesorías'),
    ('OTROS', 'Otros'),
    ('EXPEDIENTE_CONSIGNACION', 'Expediente (Consignación)'),
    ('INSP_LINDEROS', 'Inspección para Linderos'),
    ('AUT_PAGO', 'Autorización de Pago'),
    ('LIB_TIT_SUP', 'Liberaciones de Título Supletorio'),
    ('ACLARATORIA', 'Aclaratoria'),
    ('AUT_TIT_SUP', 'Autorización para Título Supletorio'),
    ('TRF_TERR', 'Transferencia de Terrenos'),
    ('SOL_LINDEROS', 'Solicitud de Linderos'),
]

ETIQUETAS_HISTORICAS = {
    'ASESORIA': 'Asesoría',
    'ASESORIA_AVV': 'Asesoría AVV',
    'RECAUDOS': 'Entrega de Recaudos',
    'RETIRO': 'Retiros de Documentos',
    'SOL_INAVI': 'Solicitud Regularización INAVI',
    'ACL_LINDEROS': 'Aclaratorias de Linderos INAVI',
    'RESP_TRIB_SUP': 'Respuesta a Tribunales - Títulos Supletorios',
    'LIB_TERR': 'Liberaciones de Terrenos',
    'SOL_INSPECCION': 'Solicitud de Inspección',
    'REG_COMERCIAL': 'Regularización Comercial',
    'CTU': 'Registro O Actualización de CTU',
    'REG_TIERRAS': 'Regularización de Tierras o Vivienda',
    'TECNICO': 'Servicios Técnicos',
    'OTRO': 'Otros',
}


def migrar_motivos_a_categorias(apps, schema_editor):
    CategoriaVisita = apps.get_model('beneficiarios', 'CategoriaVisita')
    Visita = apps.get_model('beneficiarios', 'Visita')
    categorias_por_codigo = {}

    for orden, (codigo_antiguo, nombre) in enumerate(CATEGORIAS_ACTUALES, start=1):
        categoria, _ = CategoriaVisita.objects.using(schema_editor.connection.alias).get_or_create(
            codigo=codigo_antiguo.lower(),
            defaults={'nombre': nombre, 'orden': orden, 'activa': True},
        )
        categorias_por_codigo[codigo_antiguo] = categoria

    alias_historico = 0
    visitas = Visita.objects.using(schema_editor.connection.alias).all().iterator()
    for visita in visitas:
        categoria = categorias_por_codigo.get(visita.motivo)
        if categoria is None:
            nombre = ETIQUETAS_HISTORICAS.get(
                visita.motivo,
                visita.motivo.replace('_', ' ').title() or 'Motivo histórico',
            )
            codigo = f'historico-{slugify(visita.motivo) or "sin-motivo"}'[:80]
            categoria, _ = CategoriaVisita.objects.using(schema_editor.connection.alias).get_or_create(
                codigo=codigo,
                defaults={
                    'nombre': nombre,
                    'orden': 1000 + alias_historico,
                    'activa': False,
                },
            )
            alias_historico += 1
        Visita.objects.using(schema_editor.connection.alias).filter(pk=visita.pk).update(
            categoria_id=categoria.pk,
        )


def restaurar_motivos(apps, schema_editor):
    Visita = apps.get_model('beneficiarios', 'Visita')
    alias_inverso = {codigo.lower(): codigo for codigo, _ in CATEGORIAS_ACTUALES}
    visitas = Visita.objects.using(schema_editor.connection.alias).select_related('categoria').iterator()
    for visita in visitas:
        codigo_categoria = visita.categoria.codigo
        if codigo_categoria == 'historico-sin-motivo':
            visita.motivo = ''
        elif codigo_categoria.startswith('historico-'):
            visita.motivo = codigo_categoria.removeprefix('historico-').upper().replace('-', '_')
        else:
            visita.motivo = alias_inverso.get(codigo_categoria, codigo_categoria.upper().replace('-', '_'))
        visita.save(update_fields=['motivo'])


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0008_alter_visita_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('codigo', models.SlugField(editable=False, max_length=80, unique=True)),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de visita',
                'verbose_name_plural': 'Categorías de visitas',
                'db_table': 'beneficiarios_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='visita',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='beneficiarios.categoriavisita', verbose_name='Motivo de la visita'),
        ),
        migrations.RunPython(migrar_motivos_a_categorias, restaurar_motivos),
        migrations.AlterField(
            model_name='visita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='beneficiarios.categoriavisita', verbose_name='Motivo de la visita'),
        ),
        migrations.RemoveField(
            model_name='visita',
            name='motivo',
        ),
    ]
