# Generated by Django 6.0 on 2026-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0008_remove_visita_funcionario_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='documentoexpediente',
            name='nombre_documento',
            field=models.CharField(max_length=100),
        ),
    ]
