# Generated by Django 6.0 on 2026-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0009_remove_beneficiario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
