# Generated by Django 6.0 on 2026-04-20 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0010_beneficiario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
