# Generated by Django 6.0 on 2026-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0011_alter_beneficiario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='funcionario_atiende',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funcionario que lo atiende'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiros de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('REG_COMERCIAL', 'Regularización Comercial'), ('CTU', 'Registro O Actualización de CTU'), ('REG_TIERRAS', 'Regularización de Tierras o Vivienda'), ('TECNICO', 'Servicios Técnicos'), ('OTRO', 'Otros')], max_length=20, verbose_name='Motivo de la visita'),
        ),
    ]
