# Generated by Django 6.0 on 2026-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0012_visita_funcionario_atiende_alter_visita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(choices=[('ASESORIA', 'Asesoría'), ('RECAUDOS', 'Entrega de Recaudos'), ('RETIRO', 'Retiros de Documentos'), ('SOLICITUD', 'Nueva Solicitud'), ('REG_COMERCIAL', 'Regularización Comercial'), ('CTU', 'Registro O Actualización de CTU'), ('REG_TIERRAS', 'Regularización de Tierras o Vivienda'), ('TECNICO', 'Servicios Técnicos'), ('OTRO', 'Otros')], max_length=20),
        ),
    ]
