# Generated by Django 6.0 on 2026-04-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0013_alter_visita_motivo'),
        ('territorio', '0004_unidadadscrita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='unidad_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas_atendidas', to='territorio.unidadadscrita', verbose_name='Unidad Administrativa'),
        ),
    ]
