# Generated by Django 6.0 on 2025-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    # apps/recibos/migrations/0006_auto_20251207_xxxx.py (¡El nombre puede variar!)

    dependencies = [
        ('recibos', '0005_anterior'), # Asegúrate de que esta dependencia sea la migración anterior a esta
    ]

    operations = [
        # 1. Alterar numero_recibo: CharField (anterior) -> IntegerField
        migrations.AlterField(
            model_name='recibo', # Usa el nombre de la clase de tu modelo actual
            name='numero_recibo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='N° Recibo'),
        ),
        
        # 2. Alterar usuario_creador: ForeignKey (anterior) -> CharField
        # Nota: La migración de ForeignKey a CharField REQUIERE que null=True esté activado
        migrations.AlterField(
            model_name='recibo',
            name='usuario_creador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Creador'),
        ),
        
        # 3. Alterar usuario_anulo: ForeignKey (anterior) -> CharField
        migrations.AlterField(
            model_name='recibo',
            name='usuario_anulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario que Anuló'),
        ),
        
        # Si había una columna 'usuario_creador_id' y 'usuario_anulo_id' (del ForeignKey), 
        # Django pudo haberlas intentado eliminar. Si esto ocurre, tendrás que forzar la limpieza
        # en una migración separada con RemoveField. Por ahora, probemos solo con AlterField.
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_recibo', models.IntegerField(help_text='Número consecutivo asignado al recibo.', unique=True, verbose_name='Número de Recibo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Pagador')),
                ('rif_cedula_identidad', models.CharField(max_length=20, verbose_name='Cédula/RIF')),
                ('direccion_inmueble', models.TextField(blank=True, null=True, verbose_name='Dirección del Inmueble')),
                ('ente_liquidado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ente Liquidado')),
                ('concepto', models.TextField(blank=True, null=True, verbose_name='Concepto de Pago')),
                ('categoria1', models.BooleanField(default=False, verbose_name='Título de Tierra Urbana - Adjudicación en Propiedad')),
                ('categoria2', models.BooleanField(default=False, verbose_name='Título de Tierra Urbana - Adjudicación más Vivienda')),
                ('categoria3', models.BooleanField(default=False, verbose_name='Vivienda - Tierra Municipal')),
                ('categoria4', models.BooleanField(default=False, verbose_name='Vivienda - Tierra Privada')),
                ('categoria5', models.BooleanField(default=False, verbose_name='Vivienda - Tierra INAVI/INTU')),
                ('categoria6', models.BooleanField(default=False, verbose_name='Excedentes - Con título Tierra Urbana')),
                ('categoria7', models.BooleanField(default=False, verbose_name='Excedentes - Título INAVI')),
                ('categoria8', models.BooleanField(default=False, verbose_name='Estudios Técnicos')),
                ('categoria9', models.BooleanField(default=False, verbose_name='Arrendamiento Locales Comerciales')),
                ('categoria10', models.BooleanField(default=False, verbose_name='Arrendamiento de Terrenos')),
                ('gastos_administrativos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos Adm. (Bs)')),
                ('tasa_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tasa del Día (Bs/Divisa)')),
                ('total_monto_bs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total (Bs)')),
                ('numero_transferencia', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Transferencia')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago/Emisión')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('En Revisión', 'En Revisión'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado (Banco)')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('usuario_creador', models.CharField(max_length=150, verbose_name='Usuario Creador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('usuario_anulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario que Anuló')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'db_table': 'recibos_pago',
                'ordering': ['-fecha', '-numero_recibo'],
            },
        ),
    ]
