# Generated by Django 6.0 on 2025-12-09 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA', models.DateTimeField(auto_now_add=True)),
                ('MENSAJE', models.TextField()),
                ('TIPO', models.CharField(choices=[('SUCCESS', 'Éxito'), ('ERROR', 'Error'), ('INFO', 'Información')], default='INFO', max_length=10)),
                ('USUARIO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recibos_logs',
                'ordering': ['-FECHA'],
            },
        ),
    ]
