# Generated by Django 6.0 on 2026-01-14 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recibos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
    ]
