# Generated by Django 6.0 on 2025-12-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
