# Generated by Django 6.0 on 2026-06-29 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_initial'),
        ('sellos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='aprobado_sello_dorado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibo',
            name='estatus_sello_dorado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado por Administración'), ('asignado', 'Asignado a Sello Dorado'), ('protocolizado', 'Protocolizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='recibo',
            name='fecha_aprobacion_sello',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='sello_dorado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='sellos.sellodorado'),
        ),
    ]
