# Generated by Django 6.0 on 2026-02-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_alter_recibo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='ente_liquidado',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='gastos_administrativos',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero_transferencia',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='rif_cedula_identidad',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='tasa_dia',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='total_monto_bs',
            field=models.DecimalField(decimal_places=2, help_text='Soporta montos extremadamente altos sin desbordamiento.', max_digits=19),
        ),
    ]
