# Generated by Django 6.0 on 2026-06-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_recibo_aprobado_sello_dorado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='notificado_consultoria',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
