# Generated by Django 6.0 on 2026-07-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0004_recibo_notificado_consultoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='categoria11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibo',
            name='categoria12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibo',
            name='categoria13',
            field=models.BooleanField(default=False),
        ),
    ]
