# Generated by Django 6.0 on 2026-02-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0004_alter_recibo_ente_liquidado_alter_recibo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='numero_transferencia',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
