# Generated by Django 6.0 on 2026-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0005_recibo_categoria11_recibo_categoria12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='categoria14',
            field=models.BooleanField(default=False),
        ),
    ]
