# Generated by Django 6.0 on 2026-02-26 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BienNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_identificacion', models.CharField(max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subcuenta', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_bien', models.CharField(default='Activo', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado_uso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.estado')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_sistema', models.CharField(max_length=100)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.biennacional')),
                ('empleado_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anterior', to='bienes.empleado')),
                ('empleado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nuevo', to='bienes.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.region'),
        ),
        migrations.CreateModel(
            name='UnidadTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.ciudad')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.parroquia')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='unidad_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.unidadtrabajo'),
        ),
        migrations.AddField(
            model_name='biennacional',
            name='unidad_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bienes.unidadtrabajo'),
        ),
    ]
