# Generated by Django 6.0 on 2026-02-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacional',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
