# Generated by Django 6.0 on 2026-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_biennacional_qr_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biennacional',
            name='estado_bien',
            field=models.CharField(choices=[('Buen Estado', 'Buen Estado'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('En Reparación', 'En Reparación'), ('Desincorporado', 'Desincorporado')], default='Buen Estado', max_length=30),
        ),
    ]
