# Generated by Django 6.0 on 2026-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0002_biennacional_qr_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='biennacional',
            name='jefe_inventariado',
            field=models.CharField(default=1, help_text='Quién supervisó el inventario', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biennacional',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biennacional',
            name='registro_persona',
            field=models.CharField(default=1, help_text='Persona que digita el bien', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biennacional',
            name='responsable_patrimonial',
            field=models.CharField(default=1, help_text='Autoridad patrimonial', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biennacional',
            name='estado_bien',
            field=models.CharField(choices=[('Buen Estado', 'Buen Estado'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('En Reparación', 'En Reparación'), ('Desincorporado', 'Desincorporado')], default='Buen Estado', max_length=30),
        ),
    ]
