# Generated by Django 6.0 on 2026-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0003_biennacional_jefe_inventariado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': '5. Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name_plural': '2. Estados'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': '3. Municipios'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'verbose_name_plural': '4. Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': '1. Regiones'},
        ),
        migrations.AlterModelOptions(
            name='unidadtrabajo',
            options={'verbose_name_plural': '6. Unidades de Trabajo'},
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
