# Generated by Django 6.0 on 2026-03-03 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0004_alter_ciudad_options_alter_estado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bienes.biennacional'),
        ),
        migrations.AlterField(
            model_name='movimientobien',
            name='empleado_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_anteriores', to='bienes.empleado'),
        ),
        migrations.AlterField(
            model_name='movimientobien',
            name='empleado_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_nuevos', to='bienes.empleado'),
        ),
        migrations.CreateModel(
            name='BienHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='bienes.biennacional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historial de Bienes',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
