# Generated by Django 6.0 on 2026-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['nombre'], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='codigo_comuna',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Comuna'),
        ),
    ]
