# Generated by Django 6.0 on 2026-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_alter_comuna_options_remove_comuna_codigo_comuna_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE personal_unidadadscrita RENAME TO territorio_unidadadscrita;",
            reverse_sql="ALTER TABLE territorio_unidadadscrita RENAME TO personal_unidadadscrita;"
        ),
    ]
