# Generated by Django 6.0 on 2026-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_move_unidadadscrita'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAdscrita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad Adscrita',
                'verbose_name_plural': 'Unidades Adscritas',
                'db_table': 'personal_unidadadscrita',
                'ordering': ['nombre'],
            },
        ),
    ]
