# Generated by Django 6.0 on 2026-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula/ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superusuario (Raíz)'), ('admin', 'Administrador'), ('user', 'Usuario (Lectura)')], default='user', max_length=15, verbose_name='Rol del sistema'),
        ),
    ]
