# Generated by Django 6.0 on 2026-02-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('ver_gestor_recibos', 'Acceso al Gestor de Recibos'), ('ver_gestor_clientes', 'Acceso al Gestor de Clientes'), ('ver_gestor_pagos', 'Acceso al Sistema de Pagos'), ('ver_gestor_contratos', 'Acceso al Gestor de Contratos'), ('ver_gestor_sellos', 'Acceso al Gestor de Sellos'), ('ver_gestor_documental', 'Acceso a la Gestión Documental'), ('ver_gestor_bienes', 'Acceso al Gestor de Bienes')]},
        ),
    ]
