# Generated by Django 6.0 on 2026-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_cedula_usuario_telefono_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'SuperUsuario'), ('admin', 'Administrador'), ('user', 'Usuario ')], default='user', max_length=15, verbose_name='Rol del sistema'),
        ),
    ]
