# Generated by Django 6.0 on 2026-01-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('ver_gestor_recibos', 'Acceso al Gestor de Recibos'), ('ver_gestor_clientes', 'Acceso al Gestor de Clientes'), ('ver_gestor_pagos', 'Acceso al Sistema de Pagos'), ('ver_gestor_contratos', 'Acceso al Gestor de Contratos'), ('ver_gestor_sellos', 'Acceso al Gestor de Sellos'), ('ver_gestor_documental', 'Acceso a la Gestión Documental')]},
        ),
    ]
