# Generated by Django 6.0 on 2026-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'SuperUsuario'), ('admin', 'Administrador'), ('user', 'Usuario')], default='user', max_length=15, verbose_name='Rol del sistema'),
        ),
    ]
