# Generated by Django 6.0 on 2026-06-29 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelloDorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sello', models.CharField(blank=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('asignado', 'Asignado'), ('protocolizado', 'Protocolizado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sello Dorado',
                'verbose_name_plural': 'Sellos Dorados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='sellos.sellodorado')),
            ],
            options={
                'verbose_name': 'Historial de Sello',
                'verbose_name_plural': 'Historiales de Sellos',
                'ordering': ['-fecha'],
            },
        ),
    ]
