# Generated by Django 6.0 on 2026-04-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('direccion_exacta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección Detallada')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.comuna', verbose_name='Comuna (Opcional)')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.estado', verbose_name='Estado de Residencia')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.municipio', verbose_name='Municipio')),
                ('parroquia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.parroquia', verbose_name='Parroquia')),
                ('unidad_adscrita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_asignado', to='territorio.unidadadscrita')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal Institucional',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='personal/expedientes/')),
                ('nombre_documento', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('ID', 'Documento de Identidad'), ('CV', 'Síntesis Curricular (CV)'), ('ACAD', 'Títulos Académicos y Certificaciones'), ('CONT', 'Actas de Nombramiento o Contratos'), ('OTRO', 'Otros Soportes')], default='OTRO', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_personal', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Documento de Personal',
                'verbose_name_plural': 'Documentos de Personal',
            },
        ),
    ]
