# Generated by Django 6.0 on 2026-03-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='personal/expedientes/')),
                ('nombre_documento', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('ID', 'Documento de Identidad'), ('CV', 'Síntesis Curricular (CV)'), ('ACAD', 'Títulos Académicos y Certificaciones'), ('CONT', 'Actas de Nombramiento o Contratos'), ('OTRO', 'Otros Soportes')], default='OTRO', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_personal', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Documento de Personal',
                'verbose_name_plural': 'Documentos de Personal',
            },
        ),
    ]
