# Generated by Django 6.0 on 2026-04-08 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_documentopersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAdscrita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad Adscrita',
                'verbose_name_plural': 'Unidades Adscritas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='personal',
            name='unidad_adscrita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_asignado', to='personal.unidadadscrita'),
        ),
    ]
