# Generated by Django 6.0 on 2026-04-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_unidadadscrita_alter_personal_unidad_adscrita'),
        ('territorio', '0002_alter_comuna_options_remove_comuna_codigo_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.comuna', verbose_name='Comuna (Opcional)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion_exacta',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección Detallada'),
        ),
        migrations.AddField(
            model_name='personal',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.estado', verbose_name='Estado de Residencia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='personal',
            name='parroquia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='territorio.parroquia', verbose_name='Parroquia'),
        ),
    ]
