# Generated by Django 6.0 on 2026-04-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_comuna_personal_direccion_exacta_and_more'),
        ('territorio', '0004_unidadadscrita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='unidad_adscrita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_asignado', to='territorio.unidadadscrita'),
        ),
        migrations.DeleteModel(
            name='UnidadAdscrita',
        ),
    ]
