# Generated by Django 6.0 on 2026-04-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gerente', models.CharField(default='ROSMEL DANIEL FLORES ÑAÑEZ', max_length=200)),
                ('cedula_gerente', models.CharField(default='V-13.617.999', max_length=20)),
                ('providencia_nro', models.CharField(default='020-024', max_length=100)),
                ('fecha_providencia', models.DateField(blank=True, null=True)),
                ('gaceta_nro', models.CharField(default='43.063', max_length=50)),
                ('monto_m2', models.DecimalField(decimal_places=4, default=0.001, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración INTU',
                'verbose_name_plural': 'Configuración Institucional',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='contratos/adjuntos/')),
                ('codigo_contrato', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nro. Contrato')),
                ('tipo_contrato', models.CharField(choices=[('arrendamiento', 'Arrendamiento'), ('venta', 'Venta'), ('comodato', 'Comodato (Institucional)'), ('alianza', 'Alianza Comercial'), ('titulo_tierra', 'Título de Tierra Urbana')], default='arrendamiento', max_length=50, verbose_name='Tipo de Instrumento Legal')),
                ('codigo_catastral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Catastral')),
                ('superficie_num', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Superficie (m2)')),
                ('superficie_letras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Superficie en Letras')),
                ('direccion_inmueble', models.TextField(blank=True, null=True, verbose_name='Dirección según Plano')),
                ('lindero_norte', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_sur', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_este', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_oeste', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_escaneado', models.FileField(blank=True, null=True, upload_to='contratos/expedientes/%Y/%m/', verbose_name='Contrato Digitalizado (PDF/Imagen)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('espera', 'En espera'), ('aprobado', 'Validado')], default='espera', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones de Estado')),
                ('cuerpo_contrato', models.TextField(blank=True, help_text='Contenido principal generado automáticamente')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('accion', models.CharField(blank=True, help_text='Ej: Modificación de monto, Cambio de fecha', max_length=100, null=True)),
                ('datos_cambiados', models.JSONField(blank=True, help_text='Diccionario con los cambios realizados', null=True)),
                ('observacion_tecnica', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Contrato',
                'verbose_name_plural': 'Historiales de Contratos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
