# Generated by Django 6.0 on 2026-01-30 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gerente', models.CharField(default='ROSMEL DANIEL FLORES ÑAÑEZ', max_length=200)),
                ('cedula_gerente', models.CharField(default='V-13.617.999', max_length=20)),
                ('providencia_nro', models.CharField(default='020-024', max_length=100)),
                ('fecha_providencia', models.DateField(blank=True, null=True)),
                ('gaceta_nro', models.CharField(default='43.063', max_length=50)),
                ('monto_m2', models.DecimalField(decimal_places=4, default=0.001, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración INTU',
                'verbose_name_plural': 'Configuración Institucional',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nro. Contrato')),
                ('tipo_contrato', models.CharField(default='VENTA PURA Y SIMPLE', max_length=100)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('codigo_catastral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Catastral')),
                ('superficie_num', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Superficie (m2)')),
                ('superficie_letras', models.CharField(max_length=255, null=True, verbose_name='Superficie en Letras')),
                ('direccion_inmueble', models.TextField(null=True, verbose_name='Dirección según Plano')),
                ('lindero_norte', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_sur', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_este', models.CharField(blank=True, max_length=255, null=True)),
                ('lindero_oeste', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_escaneado', models.FileField(blank=True, null=True, upload_to='contratos/expedientes/%Y/%m/', verbose_name='Contrato Digitalizado (PDF/Imagen)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('espera', 'En espera'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('cuerpo_contrato', models.TextField(blank=True, help_text='Contenido principal generado automáticamente')),
                ('version', models.PositiveIntegerField(default=1)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('beneficiarios', models.ManyToManyField(related_name='contratos', to='beneficiarios.beneficiario', verbose_name='Beneficiarios')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contratos.contrato')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
