# Generated by Django 6.0 on 2026-01-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(max_length=50, unique=True, verbose_name='Nro. Contrato')),
                ('tipo_contrato', models.CharField(help_text='Ej: Adjudicación de Terreno', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('cuerpo_contrato', models.TextField(help_text='Contenido principal y cláusulas')),
                ('version', models.PositiveIntegerField(default=1)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='beneficiarios.beneficiario')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
