# Generated by Django 6.0 on 2026-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Estado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('aprobado', 'Validado')], default='espera', max_length=20),
        ),
    ]
