# Generated by Django 6.0 on 2026-01-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_options_contrato_archivo_escaneado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gerente', models.CharField(default='ROSMEL DANIEL FLORES ÑAÑEZ', max_length=200)),
                ('cedula_gerente', models.CharField(default='V-13.617.999', max_length=20)),
                ('providencia_nro', models.CharField(default='020-024', max_length=100)),
                ('fecha_providencia', models.DateField(blank=True, null=True)),
                ('gaceta_nro', models.CharField(default='43.063', max_length=50)),
                ('monto_m2', models.DecimalField(decimal_places=4, default=0.001, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración INTU',
                'verbose_name_plural': 'Configuración Institucional',
            },
        ),
        migrations.AlterModelOptions(
            name='historialcontrato',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='contrato',
            name='codigo_catastral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Catastral'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='direccion_inmueble',
            field=models.TextField(null=True, verbose_name='Dirección según Plano'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lindero_este',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lindero_norte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lindero_oeste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='lindero_sur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='superficie_letras',
            field=models.CharField(max_length=255, null=True, verbose_name='Superficie en Letras'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='superficie_num',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Superficie (m2)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cuerpo_contrato',
            field=models.TextField(help_text='Contenido principal generado automáticamente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(default='VENTA PURA Y SIMPLE', max_length=100),
        ),
    ]
