# Generated by Django 6.0 on 2026-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contrato_prioridad_contrato_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='contratos/adjuntos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('arrendamiento', 'Arrendamiento'), ('venta', 'Venta'), ('comodato', 'Comodato (Institucional)'), ('alianza', 'Alianza Comercial'), ('titulo_tierra', 'Título de Tierra Urbana')], default='arrendamiento', max_length=50, verbose_name='Tipo de Instrumento Legal'),
        ),
    ]
