# Generated by Django 6.0 on 2026-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='direccion_inmueble',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección según Plano'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='superficie_letras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Superficie en Letras'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='superficie_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Superficie (m2)'),
        ),
    ]
