# Generated by Django 6.0 on 2026-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('contratos', '0003_configuracioninstitucional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='beneficiario',
        ),
        migrations.AddField(
            model_name='contrato',
            name='beneficiarios',
            field=models.ManyToManyField(related_name='contratos', to='beneficiarios.beneficiario', verbose_name='Beneficiarios'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codigo_contrato',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nro. Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cuerpo_contrato',
            field=models.TextField(blank=True, help_text='Contenido principal generado automáticamente'),
        ),
    ]
