# Generated by Django 6.0 on 2026-01-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_remove_contrato_beneficiario_contrato_beneficiarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
