# Generated by Django 6.0 on 2026-02-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_direccion_inmueble_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialContrato',
        ),
    ]
