# Generated by Django 6.0 on 2026-02-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_historialcontrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialcontrato',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Historial de Contrato', 'verbose_name_plural': 'Historiales de Contratos'},
        ),
    ]
