# Generated by Django 6.0 on 2026-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_historialcontrato_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcontrato',
            name='accion',
            field=models.CharField(blank=True, help_text='Ej: Modificación de monto, Cambio de fecha', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialcontrato',
            name='datos_cambiados',
            field=models.JSONField(blank=True, help_text='Diccionario con los cambios realizados', null=True),
        ),
    ]
