# Generated by Django 6.0 on 2026-03-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('modulo', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('C', 'CREACIÓN'), ('M', 'MODIFICACIÓN'), ('E', 'ELIMINACIÓN'), ('L', 'LOGIN'), ('X', 'LOGOUT'), ('F', 'FALLO DE ACCESO')], max_length=1)),
                ('descripcion', models.TextField()),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Bitácora de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
