# Generated by Django 6.0 on 2026-03-20 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('C', 'CREACIÓN'), ('M', 'MODIFICACIÓN'), ('E', 'ELIMINACIÓN'), ('L', 'INICIO DE SESIÓN'), ('S', 'CIERRE DE SESIÓN'), ('F', 'ACCESO FALLIDO')], max_length=1, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Evento'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='modulo',
            field=models.CharField(max_length=100, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Objeto'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valor_anterior',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valor_nuevo',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-timestamp'], name='auditoria_l_timesta_fc5b46_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'modulo'], name='auditoria_l_usuario_4cee66_idx'),
        ),
    ]
